[tool.poetry]
name = "pydantic-db"
version = "0.10.0"
description = ""
authors = ["Matthew Burkard <matthewjburkard@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.9.0"
case-switcher = "^1.3.0"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.35"}

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
mypy = "^0.942"
coverage = "^6.3.2"
sqlalchemy-stubs = "^0.4"
aiosqlite = "^0.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
